### ISSUE TITLE
improve autocomplete of names in database

### ISSUE THREAD

**Issue by curtislisle** [XDATA-Year-3/EntityAlignLarge#13]
Currently the autocomplete service (listnames?) just returns the first 100k names from a collection.  It seems better to debounce the input and call this service after they've typed 2 or 3 letters.  this way any name from the dataset will autocomplete.  

Should we also just do a query {'type':'node'}  on the dataset collection instead of having a separate topk_names_<type> collection?  Assumed yet, if query is not a lot slower.  Autocomplete is acceptable now, but shouldn't get too much slower.

**Comment by waxlamp** [comment]
Yes - if we index the username fields in the twitter and instagram collections, then there's no reason the queries should be slow.

**Comment by manthey** [comment]
Added in PR #31.
